name: Build and test Python package

permissions:
  contents: read

on:
  push:
    branches:
      - main
      - dev
    paths:
      - bin/**
      - src/**
      - tests/**
      - .github/workflows/build.yml
  pull_request:
    paths:
      - bin/**
      - src/**
      - tests/**
      - .github/workflows/build.yml
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:

  build:
    name: Test on ubuntu for python 3.11
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: Python info
        shell: bash -l {0}
        run: |
          which python3
          python3 --version
      - name: Upgrade pip and install dependencies
        run: |
          pip install build pytest wheel
      - name: Build the package
        run: 	python -m build
      - name: Install position-encoding
        run: |
          pip install $(ls dist/position_encoding*.whl)
      - name: Run unit tests
        run: pytest -v